CREATE TABLE MARCA (
	ID_MARCA SERIAL NOT NULL,
	DESCRIPCION CHARACTER VARYING NOT NULL,
	CONSTRAINT MARCAR_PK PRIMARY KEY (ID_MARCA)

);

INSERT INTO MARCA (DESCRIPCION) VALUES ('NIKE');
INSERT INTO MARCA (DESCRIPCION) VALUES ('ADIDAS');
INSERT INTO MARCA (DESCRIPCION) VALUES ('TOTTO');

---------------------------------------------------

CREATE TABLE PROVEEDOR(
	ID_PROVEEDOR SERIAL NOT NULL,
	NOMBRE CHARACTER VARYING NOT NULL,
	CONTACTO CHARACTER VARYING NOT NULL,
	DIRECCION CHARACTER VARYING NOT NULL,
	CELULAR CHARACTER VARYING NOT NULL,
	
	CONSTRAINT PROVEEDOR_PK PRIMARY KEY (ID_PROVEEDOR)
		
);

INSERT INTO PROVEEDOR (NOMBRE,CONTACTO,DIRECCION,CELULAR)
VALUES('La casa de las mochilas Emanuel','call center','Troncal de la costa/E25','096134529');
	
	
--------------------------------------------------

CREATE TABLE CATEGORIA (
	ID_CATEGORIA SERIAL NOT NULL,
	DESCRIPCION CHARACTER VARYING NOT NULL,
	CONSTRAINT CATEGORIA_PK PRIMARY KEY (ID_CATEGORIA )
);

INSERT INTO CATEGORIA (DESCRIPCION) VALUES('Estudiantil');
INSERT INTO CATEGORIA (DESCRIPCION) VALUES('Formales');;
INSERT INTO CATEGORIA (DESCRIPCION) VALUES('Camping');
INSERT INTO CATEGORIA (DESCRIPCION) VALUES('Antirrobo');
INSERT INTO CATEGORIA (DESCRIPCION) VALUES('Bolsos Deportivos');
INSERT INTO CATEGORIA (DESCRIPCION) VALUES('Clutch de noche');
INSERT INTO CATEGORIA (DESCRIPCION) VALUES('Luggage');

--------------------------------------------------
CREATE TABLE USUARIO(
	ID_USUARIO SERIAL NOT NULL,
	NOMBRE CHARACTER VARYING NOT NULL,
	APELLIDO CHARACTER VARYING NOT NULL,
	CORREO_ELECTRONICO CHARACTER VARYING NOT NULL,
	CONTRASENA CHARACTER VARYING NOT NULL,
	TIPO_USUARIO CHARACTER VARYING,
	
	CONSTRAINT USUARIO_PK PRIMARY KEY (ID_USUARIO)	
);


INSERT INTO USUARIO (NOMBRE, APELLIDO,CORREO_ELECTRONICO,CONTRASENA,TIPO_USUARIO) VALUES ('Karla','Pazan','karla2021@gmail.com','12345','Administrador');
INSERT INTO USUARIO (NOMBRE, APELLIDO,CORREO_ELECTRONICO,CONTRASENA,TIPO_USUARIO) VALUES ('Jonathan','Leonardo','Jonathan1997@gmail.com','12345','Cliente');
----------------------------------------------------
CREATE TABLE PRODUCTO(
	ID_PRODUCTO SERIAL NOT NULL,
	NOMBRE CHARACTER VARYING NOT NULL,
	DESCRIPCION CHARACTER VARYING NOT NULL,
	PRECIO_UNITARIO FLOAT NOT NULL,
	IMAGEN BYTEA,
	STOCK INTEGER NOT NULL,
	imagennombre CHARACTER VARYING,
	ID_MARCA INTEGER,
	ID_PROVEEDOR INTEGER,
	ID_CATEGORIA INTEGER,
	
	CONSTRAINT PRODUCTO_PK PRIMARY KEY (ID_PRODUCTO),
	CONSTRAINT MARCA_FK FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID_MARCA),
	CONSTRAINT PROVEEDOR_FK FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR),
	CONSTRAINT CATEGORIA_FK FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
	
	
);
--------------------------------------------------------------------------------------------

CREATE TABLE DIRECCION (
	ID_DIRECCION SERIAL NOT NULL,
	DESCRIPCION CHARACTER VARYING NOT NULL,
	CODIGO_POSTAL INTEGER NOT NULL,
	CIUDAD CHARACTER VARYING NOT NULL,
	ID_USUARIO INTEGER,
	CONSTRAINT DIRECCION_PK PRIMARY KEY (ID_DIRECCION),
	CONSTRAINT USUARIO_DIRE_FK FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
	
);
---------------------------------------------------------------------------------------------
CREATE TABLE PAGO(
	ID_PAGO SERIAL NOT NULL,
	METODO_PAGO CHARACTER VARYING NOT NULL,
	NOMBRE_TITULAR CHARACTER VARYING NOT NULL,
	FECHA_EXPEDICION DATE NOT NULL,
	NUMERO_TARJETA CHARACTER VARYING NOT NULL,
	CONSTRAINT PAGO_PK PRIMARY KEY (ID_PAGO)

);
---------------------------------------------------------------------------------------------

CREATE TABLE CABEZERA_FACTURA(
	ID_CABEZERA_FACTURA SERIAL NOT NULL,
	ID_DIRECCION INTEGER,
	ID_PAGO INTEGER,
	
	CONSTRAINT CABEZERA_FACTURA_PK PRIMARY KEY (ID_CABEZERA_FACTURA),
	CONSTRAINT DIRECCION_PEDI_FK FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION(ID_DIRECCION),
	CONSTRAINT PAGO_FK FOREIGN KEY(ID_PAGO) REFERENCES PAGO(ID_PAGO)
);
-------------------------------------------------------------------------------------------------
CREATE TABLE DETALLE_FACTURA(
	ID_DETALLE_FACTURA SERIAL NOT NULL,
	TOTAL FLOAT NOT NULL,
	IVA FLOAT NOT NULL,
	SUBTOTAL FLOAT NOT NULL,
	ID_CABEZERA_FACTURA INTEGER,
	ID_PRODUCTO INTEGER,
	CONSTRAINT FACTURA_PK PRIMARY KEY (ID_DETALLE_FACTURA),
	CONSTRAINT CABEZERA_FK FOREIGN KEY(ID_CABEZERA_FACTURA) REFERENCES CABEZERA_FACTURA(ID_CABEZERA_FACTURA),
	CONSTRAINT PRODUCTO_FK FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
	
);

